<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://venio.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="LicznikZnakowService" targetNamespace="http://venio.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://venio.com/" elementFormDefault="unqualified" targetNamespace="http://venio.com/" version="1.0">

  <xs:element name="policz" type="tns:policz"/>

  <xs:element name="policzResponse" type="tns:policzResponse"/>

  <xs:complexType name="policz">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="policzResponse">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="return" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="policzResponse">
    <wsdl:part element="tns:policzResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="policz">
    <wsdl:part element="tns:policz" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="LicznikZnakow">
    <wsdl:operation name="policz">
      <wsdl:input message="tns:policz" name="policz">
    </wsdl:input>
      <wsdl:output message="tns:policzResponse" name="policzResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LicznikZnakowServiceSoapBinding" type="tns:LicznikZnakow">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="policz">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="policz">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="policzResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LicznikZnakowService">
    <wsdl:port binding="tns:LicznikZnakowServiceSoapBinding" name="LicznikZnakowPort">
      <soap:address location="http://localhost:8080/LicznikZnakowWebService_war_exploded/LicznikZnakow"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>