
package com.venio.imported;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LicznikZnakowService", targetNamespace = "http://venio.com/", wsdlLocation = "http://localhost:8080/LicznikZnakowWebService_war_exploded/LicznikZnakow?wsdl")
public class LicznikZnakowService
    extends Service
{

    private final static URL LICZNIKZNAKOWSERVICE_WSDL_LOCATION;
    private final static WebServiceException LICZNIKZNAKOWSERVICE_EXCEPTION;
    private final static QName LICZNIKZNAKOWSERVICE_QNAME = new QName("http://venio.com/", "LicznikZnakowService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LicznikZnakowWebService_war_exploded/LicznikZnakow?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LICZNIKZNAKOWSERVICE_WSDL_LOCATION = url;
        LICZNIKZNAKOWSERVICE_EXCEPTION = e;
    }

    public LicznikZnakowService() {
        super(__getWsdlLocation(), LICZNIKZNAKOWSERVICE_QNAME);
    }

    public LicznikZnakowService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LICZNIKZNAKOWSERVICE_QNAME, features);
    }

    public LicznikZnakowService(URL wsdlLocation) {
        super(wsdlLocation, LICZNIKZNAKOWSERVICE_QNAME);
    }

    public LicznikZnakowService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LICZNIKZNAKOWSERVICE_QNAME, features);
    }

    public LicznikZnakowService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LicznikZnakowService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LicznikZnakow
     */
    @WebEndpoint(name = "LicznikZnakowPort")
    public LicznikZnakow getLicznikZnakowPort() {
        return super.getPort(new QName("http://venio.com/", "LicznikZnakowPort"), LicznikZnakow.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LicznikZnakow
     */
    @WebEndpoint(name = "LicznikZnakowPort")
    public LicznikZnakow getLicznikZnakowPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://venio.com/", "LicznikZnakowPort"), LicznikZnakow.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LICZNIKZNAKOWSERVICE_EXCEPTION!= null) {
            throw LICZNIKZNAKOWSERVICE_EXCEPTION;
        }
        return LICZNIKZNAKOWSERVICE_WSDL_LOCATION;
    }

}
