
package com.venio.imported;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LicznikZnakow", targetNamespace = "http://venio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LicznikZnakow {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "policz", targetNamespace = "http://venio.com/", className = "com.venio.imported.Policz")
    @ResponseWrapper(localName = "policzResponse", targetNamespace = "http://venio.com/", className = "com.venio.imported.PoliczResponse")
    public List<Integer> policz(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
