
package com.venio.imported;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Kantor", targetNamespace = "http://venio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Kantor {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sprawdzKurs", targetNamespace = "http://venio.com/", className = "com.venio.imported.SprawdzKurs")
    @ResponseWrapper(localName = "sprawdzKursResponse", targetNamespace = "http://venio.com/", className = "com.venio.imported.SprawdzKursResponse")
    public Double sprawdzKurs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sprzedaj", targetNamespace = "http://venio.com/", className = "com.venio.imported.Sprzedaj")
    @ResponseWrapper(localName = "sprzedajResponse", targetNamespace = "http://venio.com/", className = "com.venio.imported.SprzedajResponse")
    public Double sprzedaj(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1);

}
