
package com.venio.imported;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Licznik", targetNamespace = "http://venio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Licznik {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "odlicz", targetNamespace = "http://venio.com/", className = "com.venio.imported.Odlicz")
    @ResponseWrapper(localName = "odliczResponse", targetNamespace = "http://venio.com/", className = "com.venio.imported.OdliczResponse")
    public long odlicz();

}
