
package com.venio.imported;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LicznikService", targetNamespace = "http://venio.com/", wsdlLocation = "http://localhost:8080/WakacjeWebService_war_exploded/Licznik?wsdl")
public class LicznikService
    extends Service
{

    private final static URL LICZNIKSERVICE_WSDL_LOCATION;
    private final static WebServiceException LICZNIKSERVICE_EXCEPTION;
    private final static QName LICZNIKSERVICE_QNAME = new QName("http://venio.com/", "LicznikService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WakacjeWebService_war_exploded/Licznik?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LICZNIKSERVICE_WSDL_LOCATION = url;
        LICZNIKSERVICE_EXCEPTION = e;
    }

    public LicznikService() {
        super(__getWsdlLocation(), LICZNIKSERVICE_QNAME);
    }

    public LicznikService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LICZNIKSERVICE_QNAME, features);
    }

    public LicznikService(URL wsdlLocation) {
        super(wsdlLocation, LICZNIKSERVICE_QNAME);
    }

    public LicznikService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LICZNIKSERVICE_QNAME, features);
    }

    public LicznikService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LicznikService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Licznik
     */
    @WebEndpoint(name = "LicznikPort")
    public Licznik getLicznikPort() {
        return super.getPort(new QName("http://venio.com/", "LicznikPort"), Licznik.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Licznik
     */
    @WebEndpoint(name = "LicznikPort")
    public Licznik getLicznikPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://venio.com/", "LicznikPort"), Licznik.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LICZNIKSERVICE_EXCEPTION!= null) {
            throw LICZNIKSERVICE_EXCEPTION;
        }
        return LICZNIKSERVICE_WSDL_LOCATION;
    }

}
